DROP TABLE IF EXISTS USERS;
 
CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) DEFAULT NULL,
  email VARCHAR(250) DEFAULT NULL,
  skills VARCHAR(1000) DEFAULT NULL,
  password VARCHAR(250) NOT NULL,
  type VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS JOB_POST;
 
CREATE TABLE JOB_POST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  description VARCHAR(1000) DEFAULT NULL,
  keywords VARCHAR(1000) DEFAULT NULL,
  experience_min INT,
  experience_max INT,
  salary_min INT,
  salary_max INT,
  location VARCHAR(250) NOT NULL, 
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  owner INT
);

DROP TABLE IF EXISTS APPLICATION;
 
CREATE TABLE APPLICATION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_id INT ,
  job_id INT ,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(250) NOT NULL
);
